/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness probe */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log in (OAuth2 password flow) */
        post: operations["login_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange a refresh token */
        post: operations["refresh_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current principal */
        get: operations["me_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/operators": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List operators */
        get: operations["list_operators_v1_operators_get"];
        put?: never;
        /** Onboard an operator */
        post: operations["create_operator_v1_operators_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/operators/{operator_id}/api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Issue a machine API key for an operator */
        post: operations["issue_api_key_v1_operators__operator_id__api_keys_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/operators/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a user account */
        post: operations["create_user_v1_operators_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List this operator's customers */
        get: operations["list_customers_v1_customers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/customers/{customer_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a customer */
        get: operations["get_customer_v1_customers__customer_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/customers/{customer_id}/consents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List a customer's consent records */
        get: operations["list_consents_v1_customers__customer_id__consents_get"];
        put?: never;
        /** Record a consent grant/denial */
        post: operations["create_consent_v1_customers__customer_id__consents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/customers/{customer_id}/scores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Score history for a customer */
        get: operations["score_history_v1_customers__customer_id__scores_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ingest/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest repayment events inline (validated, anonymised, idempotent) */
        post: operations["ingest_events_v1_ingest_events_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ingest/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload a CSV/JSON batch (processed by the background worker) */
        post: operations["ingest_batch_upload_v1_ingest_batch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ingest/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Batch job status */
        get: operations["job_status_v1_ingest_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/score": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Score a customer (solo or pooled view) */
        post: operations["score_v1_score_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/score/cooperative": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cooperative lift: solo vs pooled, with the decision flip */
        post: operations["score_cooperative_v1_score_cooperative_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/portfolio/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Operator portfolio summary */
        get: operations["portfolio_summary_v1_portfolio_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/analytics/portfolio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cross-operator portfolio risk */
        get: operations["portfolio_v1_analytics_portfolio_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/analytics/network-effect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** AUC vs. number of pooled operators (real retraining; cached) */
        get: operations["network_effect_v1_analytics_network_effect_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cooperative health */
        get: operations["health_v1_admin_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search the audit log */
        get: operations["audit_v1_admin_audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/model": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The active scoring model */
        get: operations["active_model_v1_admin_model_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Service banner */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActiveModel */
        ActiveModel: {
            /** Version */
            version: string;
            /** Threshold */
            threshold: number;
            /** Metrics */
            metrics: {
                [key: string]: number;
            };
            /** Mlflow Run Id */
            mlflow_run_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ApiKeyCreated */
        ApiKeyCreated: {
            /** Prefix */
            prefix: string;
            /**
             * Api Key
             * @description Full key, shown once. Store it securely.
             */
            api_key: string;
            /**
             * Note
             * @default This is the only time the full key is shown.
             */
            note: string;
        };
        /** AuditEntry */
        AuditEntry: {
            /** Actor */
            actor: string;
            /** Action */
            action: string;
            /** Resource */
            resource: string;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** BatchAccepted */
        BatchAccepted: {
            /** Job Id */
            job_id: string;
            /** Status */
            status: string;
            /** Received */
            received: number;
        };
        /** Body_ingest_batch_upload_v1_ingest_batch_post */
        Body_ingest_batch_upload_v1_ingest_batch_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /** Body_login_v1_auth_login_post */
        Body_login_v1_auth_login_post: {
            /** Grant Type */
            grant_type?: string | null;
            /** Username */
            username: string;
            /**
             * Password
             * Format: password
             */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Client Id */
            client_id?: string | null;
            /**
             * Client Secret
             * Format: password
             */
            client_secret?: string | null;
        };
        /** ConsentCreate */
        ConsentCreate: {
            scope: components["schemas"]["ConsentScope"];
            /**
             * Granted
             * @default true
             */
            granted: boolean;
            /**
             * Source
             * @default api
             */
            source: string;
            /** Expires At */
            expires_at?: string | null;
        };
        /** ConsentOut */
        ConsentOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            scope: components["schemas"]["ConsentScope"];
            /** Granted */
            granted: boolean;
            /** Source */
            source: string;
            /**
             * Granted At
             * Format: date-time
             */
            granted_at: string;
            /** Expires At */
            expires_at: string | null;
        };
        /**
         * ConsentScope
         * @description What a customer has consented to. Gates enrichment and scoring.
         * @enum {string}
         */
        ConsentScope: "data_sharing" | "enrichment" | "scoring";
        /** CooperativeOut */
        CooperativeOut: {
            /**
             * Customer Id
             * Format: uuid
             */
            customer_id: string;
            solo: components["schemas"]["ScoreOut"];
            pooled: components["schemas"]["ScoreOut"];
            /** Pd Delta */
            pd_delta: number;
            /** Confidence Delta */
            confidence_delta: number;
            /** Score Delta */
            score_delta: number;
            /** Decision Flips */
            decision_flips: boolean;
            /** Lift Metric */
            lift_metric: number;
        };
        /** CooperativeScoreRequest */
        CooperativeScoreRequest: {
            /**
             * Customer Id
             * Format: uuid
             */
            customer_id: string;
        };
        /** CustomerOut */
        CustomerOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Identity Hash */
            identity_hash: string;
            /**
             * Home Operator Id
             * Format: uuid
             */
            home_operator_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /** Operators */
            operators: number;
            /** Customers */
            customers: number;
            /** Repayment Events */
            repayment_events: number;
            /** Enrichment Signals */
            enrichment_signals: number;
            /** Scored Customers */
            scored_customers: number;
            /** Active Consents */
            active_consents: number;
            /** Cooperative Lifts */
            cooperative_lifts: number;
        };
        /** HealthResponse */
        HealthResponse: {
            /** @description Overall liveness status. */
            status: components["schemas"]["HealthState"];
            /**
             * Service
             * @description Service identifier.
             */
            service: string;
            /**
             * Version
             * @description Running application version.
             */
            version: string;
            /**
             * Environment
             * @description Active deployment environment.
             */
            environment: string;
        };
        /**
         * HealthState
         * @enum {string}
         */
        HealthState: "ok" | "degraded";
        /** IngestEventsRequest */
        IngestEventsRequest: {
            /**
             * Events
             * @description Raw repayment rows to ingest
             */
            events: {
                [key: string]: unknown;
            }[];
            /**
             * Enrich
             * @default true
             */
            enrich: boolean;
        };
        /** IngestResponse */
        IngestResponse: {
            report: components["schemas"]["IngestionReport"];
            /** Customers Enriched */
            customers_enriched: number;
            /** Signals Written */
            signals_written: number;
        };
        /** IngestionReport */
        IngestionReport: {
            /**
             * Received
             * @default 0
             */
            received: number;
            /**
             * Inserted
             * @default 0
             */
            inserted: number;
            /**
             * Duplicates
             * @default 0
             */
            duplicates: number;
            /**
             * Failed
             * @default 0
             */
            failed: number;
            /**
             * Customers Created
             * @default 0
             */
            customers_created: number;
            /** Errors */
            errors?: components["schemas"]["RowError"][];
        };
        /** JobStatus */
        JobStatus: {
            /** Job Id */
            job_id: string;
            /** Status */
            status: string;
            /** Result */
            result?: {
                [key: string]: unknown;
            } | null;
        };
        /** Me */
        Me: {
            /** Kind */
            kind: string;
            /**
             * Subject Id
             * Format: uuid
             */
            subject_id: string;
            role: components["schemas"]["UserRole"];
            /** Operator Id */
            operator_id: string | null;
            /** Email */
            email?: string | null;
        };
        /** NetworkEffectResponse */
        NetworkEffectResponse: {
            /** Points */
            points: {
                [key: string]: number;
            }[];
            /**
             * Note
             * @default Empirical: the model is retrained for each cooperative size.
             */
            note: string;
        };
        /** OperatorCreate */
        OperatorCreate: {
            /** Name */
            name: string;
            /**
             * Country
             * @description ISO 3166-1 alpha-2
             */
            country: string;
        };
        /** OperatorOut */
        OperatorOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Country */
            country: string;
            status: components["schemas"]["OperatorStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * OperatorStatus
         * @description Lifecycle of a tenant (PAYG operator) in the cooperative.
         * @enum {string}
         */
        OperatorStatus: "pending" | "active" | "suspended";
        /** PortfolioAnalytics */
        PortfolioAnalytics: {
            /** Scored Customers */
            scored_customers: number;
            /** Average Default Probability */
            average_default_probability: number;
            /** Approval Rate */
            approval_rate: number;
            /** Pd Histogram */
            pd_histogram: {
                [key: string]: number;
            }[];
            /** Tier Distribution */
            tier_distribution: {
                [key: string]: number;
            };
            /** Operator Concentration */
            operator_concentration: {
                [key: string]: unknown;
            }[];
            /** Newly Bankable Customers */
            newly_bankable_customers: number;
            /** Estimated Debt Capacity Unlocked Usd */
            estimated_debt_capacity_unlocked_usd: number;
        };
        /** PortfolioSummary */
        PortfolioSummary: {
            /** Total Customers */
            total_customers: number;
            /** Scored Customers */
            scored_customers: number;
            /** Tier Distribution */
            tier_distribution: {
                [key: string]: number;
            };
            /** Approval Rate */
            approval_rate: number;
            /** Average Default Probability */
            average_default_probability: number;
            /** Estimated Losses Avoided Usd */
            estimated_losses_avoided_usd: number;
        };
        /** ReadinessResponse */
        ReadinessResponse: {
            /** @description Overall readiness status. */
            status: components["schemas"]["HealthState"];
            /**
             * Dependencies
             * @description Per-dependency readiness.
             */
            dependencies?: {
                [key: string]: components["schemas"]["HealthState"];
            };
        };
        /** RefreshRequest */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /**
         * RiskTier
         * @description Risk grade with documented PD cutoffs (defined in the scoring service).
         * @enum {string}
         */
        RiskTier: "A" | "B" | "C" | "D" | "E";
        /** RowError */
        RowError: {
            /** Index */
            index: number;
            /** Message */
            message: string;
        };
        /** ScoreHistoryItem */
        ScoreHistoryItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            view: components["schemas"]["ScoreView"];
            /** Energy Credit Score */
            energy_credit_score: number;
            /** Default Probability */
            default_probability: number;
            risk_tier: components["schemas"]["RiskTier"];
            /** Model Version */
            model_version: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ScoreOut */
        ScoreOut: {
            /**
             * Customer Id
             * Format: uuid
             */
            customer_id: string;
            view: components["schemas"]["ScoreView"];
            /** Default Probability */
            default_probability: number;
            /** Energy Credit Score */
            energy_credit_score: number;
            risk_tier: components["schemas"]["RiskTier"];
            /** Approved */
            approved: boolean;
            /** Model Version */
            model_version: string;
            /** Top Factors */
            top_factors: components["schemas"]["TopFactorOut"][];
        };
        /** ScoreRequest */
        ScoreRequest: {
            /**
             * Customer Id
             * Format: uuid
             */
            customer_id: string;
            /** @default pooled */
            view: components["schemas"]["ScoreView"];
        };
        /**
         * ScoreView
         * @description The two cooperative views — the core differentiator.
         *
         *     ``SOLO``   — features from the home operator's partial history only.
         *     ``POOLED`` — features from the full cooperative history.
         * @enum {string}
         */
        ScoreView: "solo" | "pooled";
        /** Token */
        Token: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** TopFactorOut */
        TopFactorOut: {
            /** Feature */
            feature: string;
            /** Label */
            label: string;
            /** Value */
            value: number;
            /** Contribution */
            contribution: number;
            /** Direction */
            direction: string;
        };
        /** UserCreate */
        UserCreate: {
            /** Email */
            email: string;
            /** Password */
            password: string;
            role: components["schemas"]["UserRole"];
            /** Operator Id */
            operator_id?: string | null;
        };
        /** UserOut */
        UserOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            role: components["schemas"]["UserRole"];
            /** Operator Id */
            operator_id: string | null;
        };
        /**
         * UserRole
         * @description RBAC roles. Drives authorisation in Stage 5.
         * @enum {string}
         */
        UserRole: "platform_admin" | "operator_admin" | "operator_analyst" | "lender_viewer";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
        };
    };
    login_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_login_v1_auth_login_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
        };
    };
    list_operators_v1_operators_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperatorOut"][];
                };
            };
        };
    };
    create_operator_v1_operators_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OperatorCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperatorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    issue_api_key_v1_operators__operator_id__api_keys_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                operator_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_user_v1_operators_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_customers_v1_customers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerOut"][];
                };
            };
        };
    };
    get_customer_v1_customers__customer_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                customer_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_consents_v1_customers__customer_id__consents_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                customer_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsentOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_consent_v1_customers__customer_id__consents_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                customer_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConsentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    score_history_v1_customers__customer_id__scores_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                customer_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoreHistoryItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_events_v1_ingest_events_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestEventsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_batch_upload_v1_ingest_batch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_ingest_batch_upload_v1_ingest_batch_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestResponse"] | components["schemas"]["BatchAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    job_status_v1_ingest_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    score_v1_score_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScoreRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoreOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    score_cooperative_v1_score_cooperative_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CooperativeScoreRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CooperativeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    portfolio_summary_v1_portfolio_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioSummary"];
                };
            };
        };
    };
    portfolio_v1_analytics_portfolio_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioAnalytics"];
                };
            };
        };
    };
    network_effect_v1_analytics_network_effect_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NetworkEffectResponse"];
                };
            };
        };
    };
    health_v1_admin_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    audit_v1_admin_audit_get: {
        parameters: {
            query?: {
                actor?: string | null;
                action?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    active_model_v1_admin_model_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActiveModel"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
